# Generated by Django 2.2 on 2019-05-08 16:25

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostID', models.IntegerField()),
                ('usage', models.FloatField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cpu动态表',
                'db_table': 'cpu_dynamic_info',
                'ordering': ('create_time',),
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostID', models.IntegerField()),
                ('usage', models.FloatField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'disk动态表',
                'db_table': 'disk_dynamic_info',
                'ordering': ('create_time',),
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_name', models.CharField(max_length=30)),
                ('ip', models.CharField(max_length=30)),
                ('node_type', models.CharField(max_length=30)),
                ('cpu_model', models.CharField(max_length=30)),
                ('core_num', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('disk', models.IntegerField()),
                ('isagent', models.IntegerField(default=0)),
                ('remarks', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '服务器列表',
                'db_table': 'server_info',
                'ordering': ('create_time',),
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginname', models.CharField(max_length=20)),
                ('logintime', models.CharField(max_length=20)),
                ('last_time', models.CharField(max_length=20)),
                ('ipaddress', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '登陆日志',
                'db_table': 'userlogin',
                'ordering': ('create_time',),
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostID', models.IntegerField()),
                ('receive_speed', models.CharField(max_length=50)),
                ('transmit_speed', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '网络动态表',
                'db_table': 'network_dynamic_info',
                'ordering': ('create_time',),
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostID', models.IntegerField()),
                ('usage', models.FloatField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'storage动态表',
                'db_table': 'mem_dynamic_info',
                'ordering': ('create_time',),
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=40)),
                ('academy', models.CharField(max_length=40)),
                ('classspell', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': '学生班级列表',
                'db_table': 'class',
                'ordering': ('id',),
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SysLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostID', models.IntegerField()),
                ('level', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '系统日志',
                'db_table': 'Log',
                'ordering': ('create_time',),
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('spell', models.CharField(max_length=20)),
                ('classID', models.IntegerField()),
            ],
            options={
                'verbose_name': '学生用户列表',
                'db_table': 'student',
                'ordering': ('id',),
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(default='123456', max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('homedirectory', models.CharField(blank=True, max_length=30)),
                ('groupname', models.CharField(blank=True, max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '系统用户',
                'db_table': 'user_sys',
                'ordering': ('create_time',),
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
