# Generated by Django 2.2 on 2019-04-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersystem',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
