# Generated by Django 2.2 on 2019-05-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='core_num',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='disk',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='storage',
            field=models.CharField(max_length=30),
        ),
    ]
