# Generated by Django 2.2 on 2019-04-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190417_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersystem',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
