# Generated by Django 2.2 on 2019-05-11 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190508_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstudent',
            options={'ordering': ('create_time',), 'verbose_name': '学生用户列表'},
        ),
        migrations.AddField(
            model_name='userstudent',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstudent',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='usage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='disk',
            name='usage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='storage',
            name='usage',
            field=models.CharField(max_length=50),
        ),
    ]
