# Generated by Django 2.2 on 2019-04-17 08:00

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190417_1540'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usersystem',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
