# Generated by Django 2.2 on 2019-05-11 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190511_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginlog',
            options={'ordering': ('createtime',), 'verbose_name': '登陆日志'},
        ),
        migrations.RenameField(
            model_name='loginlog',
            old_name='create_time',
            new_name='createtime',
        ),
        migrations.RenameField(
            model_name='loginlog',
            old_name='logintime',
            new_name='port',
        ),
    ]
