# Generated by Django 2.2 on 2019-04-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20190417_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_name', models.CharField(max_length=30)),
                ('ip', models.CharField(max_length=30)),
                ('node_type', models.CharField(max_length=30)),
                ('cpu_model', models.CharField(max_length=30)),
                ('core_num', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('disk', models.IntegerField()),
                ('isagent', models.BooleanField(default=False)),
                ('remarks', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
