# Generated by Django 2.2 on 2019-05-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_sysloginlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sysloginlog',
            old_name='loginname',
            new_name='loginEmail',
        ),
    ]
