# Generated by Django 2.2 on 2019-04-18 05:49

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_equipment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ('create_time',), 'verbose_name': '服务器列表'},
        ),
        migrations.AlterModelManagers(
            name='equipment',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelTable(
            name='equipment',
            table='equipment',
        ),
    ]
