# Generated by Django 2.2 on 2019-04-18 06:07

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20190418_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_id', models.IntegerField()),
                ('usage_rate', models.FloatField()),
                ('check_time', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cpu动态表',
                'db_table': 'cpu',
                'ordering': ('create_time',),
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_id', models.IntegerField()),
                ('usage_rate', models.FloatField()),
                ('check_time', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'disk动态表',
                'db_table': 'disk',
                'ordering': ('create_time',),
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_id', models.IntegerField()),
                ('usage_rate', models.FloatField()),
                ('check_time', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'storage动态表',
                'db_table': 'storage',
                'ordering': ('create_time',),
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
