# Generated by Django 2.2 on 2019-04-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_cpu_disk_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='check_time',
            field=models.TimeField(),
        ),
    ]
