# Generated by Django 2.2 on 2019-04-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20190419_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='check_time',
            field=models.DateTimeField(),
        ),
    ]
