# Generated by Django 2.2 on 2019-04-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_loginlog_syslog_userstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='login_ip',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loginlog',
            name='login_name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loginlog',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loginlog',
            name='logout_time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loginlog',
            name='terminal_type',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syslog',
            name='content',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syslog',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syslog',
            name='remarks',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstudent',
            name='academy',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstudent',
            name='class_grade',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstudent',
            name='stu_name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstudent',
            name='stu_num',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstudent',
            name='stu_password',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
