# Generated by Django 2.2 on 2019-04-19 11:41

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20190419_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_id', models.IntegerField()),
                ('soft_name', models.CharField(max_length=100)),
                ('soft_log_name', models.CharField(max_length=100)),
                ('describe', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '软件列表',
                'db_table': 'software',
                'ordering': ('create_time',),
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_id', models.IntegerField()),
                ('soft_name', models.CharField(max_length=100)),
                ('soft_log', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '软件日志',
                'db_table': 'software_log',
                'ordering': ('create_time',),
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
