# Generated by Django 2.2 on 2019-04-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_software_softwarelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='isagent',
            field=models.IntegerField(default=0),
        ),
    ]
