# Generated by Django 2.2 on 2019-04-26 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20190425_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='check_time',
        ),
        migrations.AddField(
            model_name='cpu',
            name='check_Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
