# Generated by Django 2.2 on 2019-04-26 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20190426_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='check_Date',
            new_name='check_date',
        ),
    ]
