# Generated by Django 2.2 on 2019-04-26 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20190426_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disk',
            name='check_time',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='check_time',
        ),
        migrations.AddField(
            model_name='disk',
            name='check_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='check_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
