# Generated by Django 2.2 on 2019-04-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20190426_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersystem',
            name='email',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
    ]
